{% set name = "beamngpy" %}
{% set version = "1.33.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/beamngpy-{{ version }}.tar.gz
  sha256: 16dec10c7b3258a62d72075bf312df097d7468845b37916fccf84998c791c470

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - jinja2
    - matplotlib-base
    - msgpack-python
    - numpy
    - pillow
    - python >={{ python_min }}
    - scipy
    - seaborn

test:
  imports:
    - beamngpy
    - beamngpy.sensors
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/BeamNG/BeamNGpy
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Python API to interact with BeamNG.tech.
  doc_url: https://documentation.beamng.com/api/beamngpy
  dev_url: https://github.com/BeamNG/BeamNGpy

extra:
  recipe-maintainers:
    - aivora-beamng
    - dstark481
