{% set name = "beamngpy" %}
{% set version = "1.31" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/beamngpy-{{ version }}.tar.gz
  sha256: 33a4958bb4798b83061a1814da33886e146b1a9236a10f01501d1dd6c3bc3b57

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - jinja2
    - matplotlib-base
    - msgpack-python
    - numpy
    - pillow
    - python >={{ python_min }}
    - scipy
    - seaborn

test:
  imports:
    - beamngpy
    - beamngpy.sensors
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/BeamNG/BeamNGpy
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Python API to interact with BeamNG.tech.
  doc_url: https://beamngpy.readthedocs.io
  dev_url: https://github.com/BeamNG/BeamNGpy

extra:
  recipe-maintainers:
    - aivora-beamng
    - dstark481
